### ISSUE TITLE
QR Code Generator

### ISSUE THREAD

**Issue by Harikaraja** [TusharKesarwani/Front-End-Projects#253] opened 2023-01-13 17:03 UTC
I want to create a new project called QR code generator . It takes some URL as input and generates the QR code.

**Comment by abhilipsasahoo03** [comment] 2023-01-13 17:12
Hi, I think this is a duplicate of https://github.com/TusharKesarwani/Front-End-Projects/issues/134

Kindly make sure to check that the project you're suggesting hasn't already been added or suggested before.

**Closed** 2023-01-13 21:28 UTC
Labels: duplicate
