### ISSUE TITLE
Add Accordion Menu Project

### ISSUE THREAD

**Issue by Abhay3819** [TusharKesarwani/Front-End-Projects#1497] opened 2023-06-26 17:13 UTC
## **Describe the project**
Hii @TusharKesarwani , I want to add this project so please assign to me.

## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] New Project

## **Screenshots**

![Screenshot (577)](https://github.com/TusharKesarwani/Front-End-Projects/assets/110670975/4ada9cf7-e86a-49ad-819d-88f5684ff9e6)

**Comment by Ayush9951** [comment] 2023-07-07 07:06
Hi @Arun9739, I am a contributor in ssoc'23,
If the issue is still open I would like to work on this issue, please assign it to me

**Comment by TusharKesarwani** [comment] 2023-07-11 20:39
Already present in the repo

**Closed by TusharKesarwani** 2023-07-11 20:39 UTC
Labels: wontfix
